### ISSUE TITLE
Two different keys

### ISSUE THREAD

**Issue by dercoder** [hiqdev/omnipay-interkassa#2]
There are 2 different type of keys.
Sign Key and Test Key. 
But the current version only supports one

**Comment by SilverFire** [comment]
Yes, it's not implemented yet.
`testMode` is hardcoded to `false` in [Gateway.php:38](https://github.com/hiqdev/omnipay-interkassa/blob/master/src/Gateway.php#L38).
Would you like to submit a PR?

**Comment by dercoder** [comment]
Yes sure, currently i am working on it. Also on the other "Bug"

**Comment by SilverFire** [comment]
Thank you

**Comment by dercoder** [comment]
How should i handle backward compatibility?

**Comment by SilverFire** [comment]
The extension is formally under development, we do not have releases in this repo yet. Therfore I think BC break is acceptable

**Comment by dercoder** [comment]
Great :)
And one more info: "Test Key" is not the key for  `testMode`. its the key to verify the incoming `ik_sign`
Sign Key = Key to create sign the requests (PurchaseRequest)
Test Key = Key to validate the response (CompletePurchaseResponse)

**Comment by SilverFire** [comment]
AFAIK, it is for test mode. It it used to validate the response, when payment is done using "Test payment system"

> There is “Test payment system” for testing and carrying out of payment. 
> ...
> Thus, you can test in full all process
> ...
> For this you need to use “test secret key”, that is available in checkout settings. Given
> key is used for payment notification signature of the payment that was done only via “Test payment
> system”.
> Attention! Present mechanism, with “test secret key”, prevents a situation when you webapplication
> can credit the funds of the payment which was done via “test paymentsystem”
> according to transmitted data on the interaction page (InteractionURL). For this, ALLWAYS check
> digital signature from SCI.

**Comment by dercoder** [comment]
Ok, now i understand

**Comment by dercoder** [comment]
Can you explain this?
https://github.com/hiqdev/omnipay-interkassa/blob/master/src/Message/OldPurchaseRequest.php#L25
username is undefined

**Comment by SilverFire** [comment]
Oh snap. It is our project-related internal thing that was commited accidentally. I will remove it

**Comment by hiqsol** [comment]
AFAICS test key is implemented. Closing this issues.
